/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PriceDetailInner {
    /**
    * If a breakdown is provided, details can either be; 'TAX',<BR>                              'DISCOUNT'
    */
    'priceType'?: string;
    /**
    * Discount or tax type codes as provided by DHL Express. Example values;<BR>                              For discount;<BR>                              P: promotional<BR>                              S: special<BR>                              - \"DISCOUNT\"
    */
    'typeCode'?: string;
    /**
    * The actual amount of the discount/tax
    */
    'price'?: number;
    /**
    * Percentage of the discount/tax
    */
    'rate'?: number;
    /**
    * The base amount of the service charge
    */
    'basePrice'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "priceType",
            "baseName": "priceType",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "rate",
            "baseName": "rate",
            "type": "number",
            "format": ""
        },
        {
            "name": "basePrice",
            "baseName": "basePrice",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PriceDetailInner.attributeTypeMap;
    }

    public constructor() {
    }
}

