/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductsInner1DeliveryCapabilities {
    /**
    * Delivery Date capabilities considering customs clearance days.<BR>                QDDF: is the fastest (\"docs\") transit time as quoted to the customer at booking or shipment creation. No custom clearance is considered.<BR>                QDDC: constitutes DHL's service commitment as quoted at booking/shipment creation. QDDc builds in clearance time, and potentially other special operational non-transport component(s), when relevant.
    */
    'deliveryTypeCode'?: string;
    /**
    * This is the estimated date/time the shipment will be delivered by for the rated shipment and product listed
    */
    'estimatedDeliveryDateAndTime'?: string;
    /**
    * The DHL Service Area Code for the destination of the Shipment
    */
    'destinationServiceAreaCode'?: string;
    /**
    * The DHL Facility Code for the Destination
    */
    'destinationFacilityAreaCode'?: string;
    /**
    * This is additional transit delays (in days) for shipment delivered to the<BR>                mentioned city or postal area following arrival at the service area.
    */
    'deliveryAdditionalDays'?: number;
    /**
    * Destination day of the week number
    */
    'deliveryDayOfWeek'?: number;
    /**
    * The number of transit days
    */
    'totalTransitDays'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "deliveryTypeCode",
            "baseName": "deliveryTypeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "estimatedDeliveryDateAndTime",
            "baseName": "estimatedDeliveryDateAndTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationServiceAreaCode",
            "baseName": "destinationServiceAreaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationFacilityAreaCode",
            "baseName": "destinationFacilityAreaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryAdditionalDays",
            "baseName": "deliveryAdditionalDays",
            "type": "number",
            "format": ""
        },
        {
            "name": "deliveryDayOfWeek",
            "baseName": "deliveryDayOfWeek",
            "type": "number",
            "format": ""
        },
        {
            "name": "totalTransitDays",
            "baseName": "totalTransitDays",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductsInner1DeliveryCapabilities.attributeTypeMap;
    }

    public constructor() {
    }
}

