/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductsInner1DeliveryCapabilities } from './ProductsInner1DeliveryCapabilities';
import { ProductsInner1DetailedPriceBreakdownInner } from './ProductsInner1DetailedPriceBreakdownInner';
import { ProductsInner1PickupCapabilities } from './ProductsInner1PickupCapabilities';
import { ProductsInner1TotalPriceBreakdownInner } from './ProductsInner1TotalPriceBreakdownInner';
import { ProductsInner1TotalPriceInner } from './ProductsInner1TotalPriceInner';
import { Weight1 } from './Weight1';
import { HttpFile } from '../http/http';

export class ProductsInner1 {
    /**
    * Name of the DHL Express product
    */
    'productName'?: string;
    /**
    * This is the global DHL Express product code for which the delivery is feasible respecting the input data from the request.
    */
    'productCode'?: string;
    /**
    * This is the local DHL Express product code for which the delivery is feasible respecting the input data from the request.
    */
    'localProductCode'?: string;
    /**
    * The country code for the local service used
    */
    'localProductCountryCode'?: string;
    /**
    * The NetworkTypeCode element indicates the product belongs to the Day Definite (DD) or Time Definite (TD) network.<BR>            Possible Values;<BR>             DD: Day Definite product<BR>             TD: Time Definite product
    */
    'networkTypeCode'?: string;
    /**
    * Indicator that the product only can be offered to customers with prior agreement.
    */
    'isCustomerAgreement'?: boolean;
    'weight': Weight1;
    'totalPrice': Array<ProductsInner1TotalPriceInner>;
    'totalPriceBreakdown'?: Array<ProductsInner1TotalPriceBreakdownInner>;
    'detailedPriceBreakdown'?: Array<ProductsInner1DetailedPriceBreakdownInner>;
    'pickupCapabilities'?: ProductsInner1PickupCapabilities;
    'deliveryCapabilities'?: ProductsInner1DeliveryCapabilities;
    'items'?: Array<any>;
    /**
    * The date when the rates for DHL products and services is provided
    */
    'pricingDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productName",
            "baseName": "productName",
            "type": "string",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCode",
            "baseName": "localProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCountryCode",
            "baseName": "localProductCountryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "networkTypeCode",
            "baseName": "networkTypeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCustomerAgreement",
            "baseName": "isCustomerAgreement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "Weight1",
            "format": ""
        },
        {
            "name": "totalPrice",
            "baseName": "totalPrice",
            "type": "Array<ProductsInner1TotalPriceInner>",
            "format": ""
        },
        {
            "name": "totalPriceBreakdown",
            "baseName": "totalPriceBreakdown",
            "type": "Array<ProductsInner1TotalPriceBreakdownInner>",
            "format": ""
        },
        {
            "name": "detailedPriceBreakdown",
            "baseName": "detailedPriceBreakdown",
            "type": "Array<ProductsInner1DetailedPriceBreakdownInner>",
            "format": ""
        },
        {
            "name": "pickupCapabilities",
            "baseName": "pickupCapabilities",
            "type": "ProductsInner1PickupCapabilities",
            "format": ""
        },
        {
            "name": "deliveryCapabilities",
            "baseName": "deliveryCapabilities",
            "type": "ProductsInner1DeliveryCapabilities",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<any>",
            "format": ""
        },
        {
            "name": "pricingDate",
            "baseName": "pricingDate",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductsInner1.attributeTypeMap;
    }

    public constructor() {
    }
}

