/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductsInnerBreakdownInner {
    /**
    * Breakdown Name
    */
    'name'?: string;
    /**
    * Special service or extra charge code.  This is the code you would have to use in the /shipment service if you wish to add an optional Service such as Saturday delivery
    */
    'serviceCode'?: string;
    /**
    * Local service code
    */
    'localServiceCode'?: string;
    /**
    * Breakdown type code
    */
    'typeCode'?: string;
    /**
    * Special service charge code type for service.
    */
    'serviceTypeCode'?: string;
    /**
    * Customer agreement indicator for product and services, if service is offered with prior customer agreement
    */
    'isCustomerAgreement'?: boolean;
    /**
    * Indicator if the special service is marketed service
    */
    'isMarketedService'?: boolean;
    /**
    * Indicator if there is any discount allowed
    */
    'isBillingServiceIndicator'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceCode",
            "baseName": "serviceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localServiceCode",
            "baseName": "localServiceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceTypeCode",
            "baseName": "serviceTypeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCustomerAgreement",
            "baseName": "isCustomerAgreement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMarketedService",
            "baseName": "isMarketedService",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isBillingServiceIndicator",
            "baseName": "isBillingServiceIndicator",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductsInnerBreakdownInner.attributeTypeMap;
    }

    public constructor() {
    }
}

