/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PriceDetailInner } from './PriceDetailInner';
import { HttpFile } from '../http/http';

export class ProductsInner1DetailedPriceBreakdownInnerBreakdownInner {
    /**
    * When landed-cost is requested then following items name (Charge Types) might be returned: <BR>                        Charge Type : Description <BR>                        STDIS : Quoted shipment total discount <BR>                        SCUSV : Shipment Customs value <BR>                        SINSV : Insured value <BR>                        SPRQD : Shipment product quote discount<BR>                        SPRQN : The price quoted to the Customer by DHL at the time of the booking. This quote covers the weight price including discounts and without taxes. <BR>                        STSCH : The total of service charges quoted to customer for DHL Express value added services, the amount is after discounts and doesn't include tax amounts. <BR>                        MACHG : The total of service charges as provided by Merchant for the purpose of landed cost calculation. <BR>                        MFCHG : The freight charge as provided by Merchant for the purpose of landed cost calculation.
    */
    'name'?: string;
    /**
    * Special service or extra charge code. This is the code you would have to use in the /shipment service if you wish to add an optional Service such as Saturday delivery
    */
    'serviceCode'?: string;
    /**
    * Local service code
    */
    'localServiceCode'?: string;
    /**
    * Price breakdown type code
    */
    'typeCode'?: string;
    /**
    * Special service charge code type for service.
    */
    'serviceTypeCode'?: string;
    /**
    * Price breakdown value
    */
    'price'?: number;
    /**
    * This the currency of the rated shipment for the prices listed.
    */
    'priceCurrency'?: string;
    /**
    * Customer agreement indicator for product and services, if service is offered with prior customer agreement
    */
    'isCustomerAgreement'?: boolean;
    /**
    * Indicator if the special service is marketed service
    */
    'isMarketedService'?: boolean;
    /**
    * Indicator if there is any discount allowed
    */
    'isBillingServiceIndicator'?: boolean;
    'priceBreakdown'?: Array<PriceDetailInner>;
    /**
    * Tariff Rate Formula on Shipment Level
    */
    'tariffRateFormula'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceCode",
            "baseName": "serviceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localServiceCode",
            "baseName": "localServiceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceTypeCode",
            "baseName": "serviceTypeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "price",
            "baseName": "price",
            "type": "number",
            "format": ""
        },
        {
            "name": "priceCurrency",
            "baseName": "priceCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCustomerAgreement",
            "baseName": "isCustomerAgreement",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isMarketedService",
            "baseName": "isMarketedService",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isBillingServiceIndicator",
            "baseName": "isBillingServiceIndicator",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "priceBreakdown",
            "baseName": "priceBreakdown",
            "type": "Array<PriceDetailInner>",
            "format": ""
        },
        {
            "name": "tariffRateFormula",
            "baseName": "tariffRateFormula",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductsInner1DetailedPriceBreakdownInnerBreakdownInner.attributeTypeMap;
    }

    public constructor() {
    }
}

