/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ProductsInner1PickupCapabilities {
    /**
    * This indicator has values of Y or N, and tells the consumer if the service in the response has a pickup date on the same day as the requested shipment date (per the request).
    */
    'nextBusinessDay'?: boolean;
    /**
    * This is the cutoff time for the service<BR>                offered in the response. This represents the latest time (local to origin) which the shipment can be tendered to the courier for that service on that day.
    */
    'localCutoffDateAndTime'?: string;
    /**
    * Pickup cut off time in GMT
    */
    'gMTCutoffTime'?: string;
    /**
    * The DHL earliest time possible for pickup
    */
    'pickupEarliest'?: string;
    /**
    * The DHL latest time possible for pickup
    */
    'pickupLatest'?: string;
    /**
    * The DHL Service Area Code for the origin of the Shipment
    */
    'originServiceAreaCode'?: string;
    /**
    * The DHL Facility Code for the Origin
    */
    'originFacilityAreaCode'?: string;
    /**
    * This is additional transit delays (in days) for shipment picked up from the mentioned city or postal area to arrival at the service area.
    */
    'pickupAdditionalDays'?: number;
    /**
    * Pickup day of the week number
    */
    'pickupDayOfWeek'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "nextBusinessDay",
            "baseName": "nextBusinessDay",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "localCutoffDateAndTime",
            "baseName": "localCutoffDateAndTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "gMTCutoffTime",
            "baseName": "GMTCutoffTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "pickupEarliest",
            "baseName": "pickupEarliest",
            "type": "string",
            "format": ""
        },
        {
            "name": "pickupLatest",
            "baseName": "pickupLatest",
            "type": "string",
            "format": ""
        },
        {
            "name": "originServiceAreaCode",
            "baseName": "originServiceAreaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "originFacilityAreaCode",
            "baseName": "originFacilityAreaCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "pickupAdditionalDays",
            "baseName": "pickupAdditionalDays",
            "type": "number",
            "format": ""
        },
        {
            "name": "pickupDayOfWeek",
            "baseName": "pickupDayOfWeek",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductsInner1PickupCapabilities.attributeTypeMap;
    }

    public constructor() {
    }
}

