/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInner {
    /**
    * Please enter type of prepaid charge. At this moment only freight is supported
    */
    'typeCode': SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerTypeCodeEnum;
    /**
    * Please enter currency for the value you have entered into value field
    */
    'currency': string;
    /**
    * Please enter nominal value related to the charge
    */
    'value': number;
    /**
    * Please enter method you have used to pay the charges. At this moment only cash is supported
    */
    'method': SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerMethodEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerTypeCodeEnum",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerMethodEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerTypeCodeEnum = "freight" ;
export type SupermodelIoLogisticsExpressCreateShipmentRequestPrepaidChargesInnerMethodEnum = "cash" ;

