/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo } from './SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo';
import { SupermodelIoLogisticsExpressCreateShipmentResponseDocumentsInner } from './SupermodelIoLogisticsExpressCreateShipmentResponseDocumentsInner';
import { SupermodelIoLogisticsExpressCreateShipmentResponseEstimatedDeliveryDate } from './SupermodelIoLogisticsExpressCreateShipmentResponseEstimatedDeliveryDate';
import { SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner } from './SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentChargesInner } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentChargesInner';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner';
import { HttpFile } from '../http/http';

/**
* MyDHL API REST /shipments response schema
*/
export class SupermodelIoLogisticsExpressCreateShipmentResponse {
    /**
    * URL where the request has been sent to
    */
    'url'?: string;
    /**
    * Here you will receive Shipment Identification Number of your package
    */
    'shipmentTrackingNumber'?: string;
    /**
    * If you requested pickup for your shipment you can use this URL to cancel the pickup
    */
    'cancelPickupUrl'?: string;
    /**
    * You can use ths URL to track your shipment
    */
    'trackingUrl'?: string;
    /**
    * If you asked for pickup service here you will find Dispach Confirmation Number which identifies your pickup booking
    */
    'dispatchConfirmationNumber'?: string;
    /**
    * Here you can find information for all pieces your shipment is having like Piece Identification Number 
    */
    'packages'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner>;
    /**
    * Here you can find all documents created for the shipment like Transport and WaybillDoc labels, Invoice, Receipt
    */
    'documents'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseDocumentsInner>;
    /**
    * In this field you will find the On Demand Delivery (ODD) URL link if requested
    */
    'onDemandDeliveryURL'?: string;
    /**
    * Here you can find additional information related to your shipment when you ask for it in the request
    */
    'shipmentDetails'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner>;
    /**
    * Here you can find rates related to your shipment
    */
    'shipmentCharges'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentChargesInner>;
    'barcodeInfo'?: SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo;
    'estimatedDeliveryDate'?: SupermodelIoLogisticsExpressCreateShipmentResponseEstimatedDeliveryDate;
    'warnings'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentTrackingNumber",
            "baseName": "shipmentTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "cancelPickupUrl",
            "baseName": "cancelPickupUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingUrl",
            "baseName": "trackingUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "dispatchConfirmationNumber",
            "baseName": "dispatchConfirmationNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner>",
            "format": ""
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponseDocumentsInner>",
            "format": ""
        },
        {
            "name": "onDemandDeliveryURL",
            "baseName": "onDemandDeliveryURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentDetails",
            "baseName": "shipmentDetails",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner>",
            "format": ""
        },
        {
            "name": "shipmentCharges",
            "baseName": "shipmentCharges",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentChargesInner>",
            "format": ""
        },
        {
            "name": "barcodeInfo",
            "baseName": "barcodeInfo",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo",
            "format": ""
        },
        {
            "name": "estimatedDeliveryDate",
            "baseName": "estimatedDeliveryDate",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseEstimatedDeliveryDate",
            "format": ""
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

