/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodesInner } from './SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodesInner';
import { HttpFile } from '../http/http';

/**
* Here you can find barcode details in base64
*/
export class SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo {
    /**
    * Barcode base64 encoded airwaybill number
    */
    'shipmentIdentificationNumberBarcodeContent'?: string;
    /**
    * Barcode base64 image of origin service area code, destination service area code and global product code
    */
    'originDestinationServiceTypeBarcodeContent'?: string;
    /**
    * Barcode base64 image of DHL routing code
    */
    'routingBarcodeContent'?: string;
    /**
    * Here you can find barcode details for each piece
    */
    'trackingNumberBarcodes'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipmentIdentificationNumberBarcodeContent",
            "baseName": "shipmentIdentificationNumberBarcodeContent",
            "type": "string",
            "format": ""
        },
        {
            "name": "originDestinationServiceTypeBarcodeContent",
            "baseName": "originDestinationServiceTypeBarcodeContent",
            "type": "string",
            "format": ""
        },
        {
            "name": "routingBarcodeContent",
            "baseName": "routingBarcodeContent",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingNumberBarcodes",
            "baseName": "trackingNumberBarcodes",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfoTrackingNumberBarcodesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentResponseBarcodeInfo.attributeTypeMap;
    }

    public constructor() {
    }
}

