/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Dimensions1 } from './Dimensions1';
import { HttpFile } from '../http/http';

/**
* Package defintion for rating related services
*/
export class SupermodelIoLogisticsExpressPackageRR {
    /**
    * Please contact your DHL Express representative if you wish to use a DHL specific package otherwise ignore this element.
    */
    'typeCode'?: SupermodelIoLogisticsExpressPackageRRTypeCodeEnum;
    /**
    * The weight of the package.
    */
    'weight': number;
    'dimensions': Dimensions1;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "SupermodelIoLogisticsExpressPackageRRTypeCodeEnum",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Dimensions1",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressPackageRR.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressPackageRRTypeCodeEnum = "3BX" | "2BC" | "2BP" | "CE1" | "7BX" | "6BX" | "4BX" | "2BX" | "1CE" | "WB1" | "WB3" | "XPD" | "8BX" | "5BX" | "WB6" | "TBL" | "TBS" | "WB2" ;

