/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressAccount } from './SupermodelIoLogisticsExpressAccount';
import { SupermodelIoLogisticsExpressPackageRR } from './SupermodelIoLogisticsExpressPackageRR';
import { SupermodelIoLogisticsExpressValueAddedServicesRates } from './SupermodelIoLogisticsExpressValueAddedServicesRates';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressPickupRequestShipmentDetailsInner {
    /**
    * Please provide DHL Express Global product code of the shipment
    */
    'productCode': string;
    /**
    * Please provide DHL Express Local product code of the shipment
    */
    'localProductCode'?: string;
    /**
    * Please enter all the DHL Express accounts related to this shipment
    */
    'accounts'?: Array<SupermodelIoLogisticsExpressAccount>;
    /**
    * This section communicates additional shipping services, such as Insurance (or Shipment Value Protection).
    */
    'valueAddedServices'?: Array<SupermodelIoLogisticsExpressValueAddedServicesRates>;
    /**
    * For customs purposes please advise if your shipment is dutiable (true) or non dutiable (false)
    */
    'isCustomsDeclarable': boolean;
    /**
    * For customs purposes please advise on declared value of the shipment
    */
    'declaredValue'?: number;
    /**
    * For customs purposes please advise on declared value currency code of the shipment
    */
    'declaredValueCurrency'?: string;
    /**
    * Please enter Unit of measurement - metric,imperial
    */
    'unitOfMeasurement': SupermodelIoLogisticsExpressPickupRequestShipmentDetailsInnerUnitOfMeasurementEnum;
    /**
    * Please provide Shipment Identification number (AWB number)
    */
    'shipmentTrackingNumber'?: string;
    /**
    * Here you can define properties per package
    */
    'packages': Array<SupermodelIoLogisticsExpressPackageRR>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCode",
            "baseName": "localProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<SupermodelIoLogisticsExpressAccount>",
            "format": ""
        },
        {
            "name": "valueAddedServices",
            "baseName": "valueAddedServices",
            "type": "Array<SupermodelIoLogisticsExpressValueAddedServicesRates>",
            "format": ""
        },
        {
            "name": "isCustomsDeclarable",
            "baseName": "isCustomsDeclarable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "declaredValue",
            "baseName": "declaredValue",
            "type": "number",
            "format": ""
        },
        {
            "name": "declaredValueCurrency",
            "baseName": "declaredValueCurrency",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitOfMeasurement",
            "baseName": "unitOfMeasurement",
            "type": "SupermodelIoLogisticsExpressPickupRequestShipmentDetailsInnerUnitOfMeasurementEnum",
            "format": ""
        },
        {
            "name": "shipmentTrackingNumber",
            "baseName": "shipmentTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<SupermodelIoLogisticsExpressPackageRR>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressPickupRequestShipmentDetailsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressPickupRequestShipmentDetailsInnerUnitOfMeasurementEnum = "metric" | "imperial" ;

