/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOfOneOf } from './SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOfOneOf';
import { SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOfOneOf1 } from './SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOfOneOf1';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOf {
    /**
    * Please enter dry ice total net weight when shipping dry ice
    */
    'dryIceTotalNetWeight1': number;
    /**
    * Please enter comma separated UN code(s)
    */
    'unCode': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dryIceTotalNetWeight1",
            "baseName": "dryIceTotalNetWeight1",
            "type": "number",
            "format": ""
        },
        {
            "name": "unCode",
            "baseName": "unCode",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOf.attributeTypeMap;
    }

    public constructor() {
    }
}

