/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressAddressCreateShipmentResponse {
    /**
    * Postal code
    */
    'postalCode': string;
    /**
    * City name
    */
    'cityName': string;
    /**
    * Country code
    */
    'countryCode': string;
    /**
    * Province or state code
    */
    'provinceCode'?: string;
    /**
    * Address line 1
    */
    'addressLine1': string;
    /**
    * Address line 2
    */
    'addressLine2'?: string;
    /**
    * Address line 3
    */
    'addressLine3'?: string;
    /**
    * Suburb or county name
    */
    'cityDistrictName'?: string;
    /**
    * Please enter your state or province name
    */
    'provinceName'?: string;
    /**
    * Please enter your country name
    */
    'countryName'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "postalCode",
            "baseName": "postalCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "cityName",
            "baseName": "cityName",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryCode",
            "baseName": "countryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "provinceCode",
            "baseName": "provinceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressLine1",
            "baseName": "addressLine1",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressLine2",
            "baseName": "addressLine2",
            "type": "string",
            "format": ""
        },
        {
            "name": "addressLine3",
            "baseName": "addressLine3",
            "type": "string",
            "format": ""
        },
        {
            "name": "cityDistrictName",
            "baseName": "cityDistrictName",
            "type": "string",
            "format": ""
        },
        {
            "name": "provinceName",
            "baseName": "provinceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "countryName",
            "baseName": "countryName",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressAddressCreateShipmentResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

