/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails';
import { SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails } from './SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails';
import { HttpFile } from '../http/http';

/**
* Here you need to define all the parties needed to ship the package
*/
export class SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails {
    'shipperDetails': SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails;
    'receiverDetails': SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails;
    'buyerDetails'?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails;
    'importerDetails'?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails;
    'exporterDetails'?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails;
    'sellerDetails'?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails;
    'payerDetails'?: SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipperDetails",
            "baseName": "shipperDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsShipperDetails",
            "format": ""
        },
        {
            "name": "receiverDetails",
            "baseName": "receiverDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsReceiverDetails",
            "format": ""
        },
        {
            "name": "buyerDetails",
            "baseName": "buyerDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsBuyerDetails",
            "format": ""
        },
        {
            "name": "importerDetails",
            "baseName": "importerDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsImporterDetails",
            "format": ""
        },
        {
            "name": "exporterDetails",
            "baseName": "exporterDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsExporterDetails",
            "format": ""
        },
        {
            "name": "sellerDetails",
            "baseName": "sellerDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsSellerDetails",
            "format": ""
        },
        {
            "name": "payerDetails",
            "baseName": "payerDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetailsPayerDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentRequestCustomerDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

