/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Dimensions2 } from './Dimensions2';
import { Dimensions3 } from './Dimensions3';
import { SupermodelIoLogisticsExpressReference } from './SupermodelIoLogisticsExpressReference';
import { SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInnerEventsInner } from './SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInnerEventsInner';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner {
    'number'?: number;
    'typeCode'?: string;
    'shipmentTrackingNumber'?: string;
    'trackingNumber'?: string;
    'description'?: string;
    /**
    * The weight of the package.
    */
    'weight'?: number;
    /**
    * The weight of the package.
    */
    'dimensionalWeight'?: number;
    /**
    * The weight of the package.
    */
    'actualWeight'?: number;
    'dimensions'?: Dimensions2;
    'actualDimensions'?: Dimensions3;
    'unitOfMeasurements'?: string;
    'shipperReferences'?: Array<SupermodelIoLogisticsExpressReference>;
    'events': Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInnerEventsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "number",
            "baseName": "number",
            "type": "number",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentTrackingNumber",
            "baseName": "shipmentTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingNumber",
            "baseName": "trackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "weight",
            "baseName": "weight",
            "type": "number",
            "format": ""
        },
        {
            "name": "dimensionalWeight",
            "baseName": "dimensionalWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "actualWeight",
            "baseName": "actualWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "dimensions",
            "baseName": "dimensions",
            "type": "Dimensions2",
            "format": ""
        },
        {
            "name": "actualDimensions",
            "baseName": "actualDimensions",
            "type": "Dimensions3",
            "format": ""
        },
        {
            "name": "unitOfMeasurements",
            "baseName": "unitOfMeasurements",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipperReferences",
            "baseName": "shipperReferences",
            "type": "Array<SupermodelIoLogisticsExpressReference>",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInnerEventsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

