/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesInner';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocumentsInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocumentsInner';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationDeclarationNotesInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationDeclarationNotesInner';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExporter } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExporter';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoice } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoice';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLicensesInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLicensesInner';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLineItemsInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLineItemsInner';
import { SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationRemarksInner } from './SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationRemarksInner';
import { HttpFile } from '../http/http';

/**
* Here you can find all details related to export declaration
*/
export class SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclaration {
    /**
    * Please enter details for each export line item
    */
    'lineItems': Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLineItemsInner>;
    'invoice'?: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoice;
    /**
    * Please enter up to three remarks. <BR>              If using Customs Invoice template COMMERCIAL_INVOICE_04, the invoice can only print the first remarks field. The recommended max length is 20 characters. <BR>              If using Customs Invoice template COMMERCIAL_INVOICE_L_10 or COMMERCIAL_INVOICE_P_10, the invoice can print all three remraks fields.  The recommended max length is 45 characters.
    */
    'remarks'?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationRemarksInner>;
    /**
    * Please enter additional charge to appear on the invoice<BR>              admin, Administration Charge<BR>              delivery, Delivery Charge<BR>              documentation, Documentation Charge<BR>              expedite, Expedite Charge<BR>              freight, Freight Charge<BR>              fuel surcharge, Fuel Surcharge<BR>              logistic, Logistic Charge<BR>              other, Other Charge<BR>              packaging, Packaging Charge<BR>              pickup, Pickup Charge<BR>              handling, Handling Charge<BR>              vat, VAT Charge<BR>              insurance, Insurance Cost<BR>              reverse_charge, Reverse Charge
    */
    'additionalCharges'?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesInner>;
    /**
    * Please provide destination port details
    */
    'destinationPortName'?: string;
    /**
    * Name of port of departure, shipment or destination as required under the applicable delivery term.
    */
    'placeOfIncoterm'?: string;
    /**
    * Please provide Payer VAT number
    */
    'payerVATNumber'?: string;
    /**
    * Please enter recipient reference
    */
    'recipientReference'?: string;
    'exporter'?: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExporter;
    /**
    * Please enter package marks
    */
    'packageMarks'?: string;
    /**
    * Please provide up to three dcelaration notes
    */
    'declarationNotes'?: Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationDeclarationNotesInner>;
    /**
    * Please enter export reference
    */
    'exportReference'?: string;
    /**
    * Please enter export reason
    */
    'exportReason'?: string;
    /**
    * Please provide the reason for export
    */
    'exportReasonType'?: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExportReasonTypeEnum;
    /**
    * Please provide details about export and import licenses
    */
    'licenses'?: Set<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLicensesInner>;
    /**
    * Please provide the shipment was sent for Personal (Gift) or Commercial (Sale) reasons
    */
    'shipmentType'?: SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationShipmentTypeEnum;
    /**
    * Please provide the Customs Documents at invoice level
    */
    'customsDocuments'?: Set<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocumentsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "lineItems",
            "baseName": "lineItems",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLineItemsInner>",
            "format": ""
        },
        {
            "name": "invoice",
            "baseName": "invoice",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationInvoice",
            "format": ""
        },
        {
            "name": "remarks",
            "baseName": "remarks",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationRemarksInner>",
            "format": ""
        },
        {
            "name": "additionalCharges",
            "baseName": "additionalCharges",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationAdditionalChargesInner>",
            "format": ""
        },
        {
            "name": "destinationPortName",
            "baseName": "destinationPortName",
            "type": "string",
            "format": ""
        },
        {
            "name": "placeOfIncoterm",
            "baseName": "placeOfIncoterm",
            "type": "string",
            "format": ""
        },
        {
            "name": "payerVATNumber",
            "baseName": "payerVATNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "recipientReference",
            "baseName": "recipientReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "exporter",
            "baseName": "exporter",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExporter",
            "format": ""
        },
        {
            "name": "packageMarks",
            "baseName": "packageMarks",
            "type": "string",
            "format": ""
        },
        {
            "name": "declarationNotes",
            "baseName": "declarationNotes",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationDeclarationNotesInner>",
            "format": ""
        },
        {
            "name": "exportReference",
            "baseName": "exportReference",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportReason",
            "baseName": "exportReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportReasonType",
            "baseName": "exportReasonType",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExportReasonTypeEnum",
            "format": ""
        },
        {
            "name": "licenses",
            "baseName": "licenses",
            "type": "Set<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationLicensesInner>",
            "format": ""
        },
        {
            "name": "shipmentType",
            "baseName": "shipmentType",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationShipmentTypeEnum",
            "format": ""
        },
        {
            "name": "customsDocuments",
            "baseName": "customsDocuments",
            "type": "Set<SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationCustomsDocumentsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclaration.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationExportReasonTypeEnum = "permanent" | "temporary" | "return" | "used_exhibition_goods_to_origin" | "intercompany_use" | "commercial_purpose_or_sale" | "personal_belongings_or_personal_use" | "sample" | "gift" | "return_to_origin" | "warranty_replacement" | "diplomatic_goods" | "defence_material" ;
export type SupermodelIoLogisticsExpressCreateShipmentRequestContentExportDeclarationShipmentTypeEnum = "personal" | "commercial" ;

