/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOf } from './SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInnerAnyOf';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInner {
    /**
    * Please enter valid DHL Express Dangerous good content id (please contact your DHL Express IT representative for the relevant content ID code if you are shipping Dan
    */
    'contentId': string;
    /**
    * Please enter dry ice total net weight when shipping dry ice
    */
    'dryIceTotalNetWeight'?: number;
    /**
    * Please enter comma separated UN code(s)
    */
    'unCode'?: string;
    /**
    * Please enter dry ice total net weight when shipping dry ice
    */
    'dryIceTotalNetWeight1': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "contentId",
            "baseName": "contentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "dryIceTotalNetWeight",
            "baseName": "dryIceTotalNetWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "unCode",
            "baseName": "unCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "dryIceTotalNetWeight1",
            "baseName": "dryIceTotalNetWeight1",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressValueAddedServicesDangerousGoodsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

