/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressReference } from './SupermodelIoLogisticsExpressReference';
import { SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerEventsInner } from './SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerEventsInner';
import { SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner } from './SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner';
import { SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerReceiverDetails } from './SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerReceiverDetails';
import { SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerShipperDetails } from './SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerShipperDetails';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressTrackingResponseShipmentsInner {
    'shipmentTrackingNumber'?: string;
    'status'?: string;
    'shipmentTimestamp'?: string;
    /**
    * DHL product code
    */
    'productCode'?: string;
    'description'?: string;
    'shipperDetails'?: SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerShipperDetails;
    'receiverDetails'?: SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerReceiverDetails;
    'totalWeight'?: number;
    'unitOfMeasurements'?: string;
    'shipperReferences'?: Array<SupermodelIoLogisticsExpressReference>;
    'events': Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerEventsInner>;
    'numberOfPieces'?: number;
    'pieces'?: Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner>;
    'estimatedDeliveryDate'?: string;
    'childrenShipmentIdentificationNumbers'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipmentTrackingNumber",
            "baseName": "shipmentTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipmentTimestamp",
            "baseName": "shipmentTimestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipperDetails",
            "baseName": "shipperDetails",
            "type": "SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerShipperDetails",
            "format": ""
        },
        {
            "name": "receiverDetails",
            "baseName": "receiverDetails",
            "type": "SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerReceiverDetails",
            "format": ""
        },
        {
            "name": "totalWeight",
            "baseName": "totalWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "unitOfMeasurements",
            "baseName": "unitOfMeasurements",
            "type": "string",
            "format": ""
        },
        {
            "name": "shipperReferences",
            "baseName": "shipperReferences",
            "type": "Array<SupermodelIoLogisticsExpressReference>",
            "format": ""
        },
        {
            "name": "events",
            "baseName": "events",
            "type": "Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerEventsInner>",
            "format": ""
        },
        {
            "name": "numberOfPieces",
            "baseName": "numberOfPieces",
            "type": "number",
            "format": ""
        },
        {
            "name": "pieces",
            "baseName": "pieces",
            "type": "Array<SupermodelIoLogisticsExpressTrackingResponseShipmentsInnerPiecesInner>",
            "format": ""
        },
        {
            "name": "estimatedDeliveryDate",
            "baseName": "estimatedDeliveryDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "childrenShipmentIdentificationNumbers",
            "baseName": "childrenShipmentIdentificationNumbers",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressTrackingResponseShipmentsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

