/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInner {
    /**
    * Please enter channel type to send the notification by. At this moment only email is supported
    */
    'typeCode': SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTypeCodeEnum;
    /**
    * Please enter notification receiver email address
    */
    'receiverId': string;
    /**
    * Please enter three letter lanuage code in which you wish to receive the notification in
    */
    'languageCode'?: string;
    /**
    * Please enter two letter language country code
    */
    'languageCountryCode'?: string;
    /**
    * Please enter your message which will be added to the DHL Express notification email
    */
    'bespokeMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTypeCodeEnum",
            "format": ""
        },
        {
            "name": "receiverId",
            "baseName": "receiverId",
            "type": "string",
            "format": ""
        },
        {
            "name": "languageCode",
            "baseName": "languageCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "languageCountryCode",
            "baseName": "languageCountryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "bespokeMessage",
            "baseName": "bespokeMessage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressCreateShipmentRequestShipmentNotificationInnerTypeCodeEnum = "email" ;

