/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInnerDocumentsInner } from './SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInnerDocumentsInner';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner {
    /**
    * Piece serial number
    */
    'referenceNumber'?: number;
    /**
    * Here is provided each piece its Identification number
    */
    'trackingNumber': string;
    /**
    * You can use ths URL to track your shipment by Piece Identification Number
    */
    'trackingUrl'?: string;
    /**
    * Here is provided each piece volumetric/ dimensional weight
    */
    'volumetricWeight'?: number;
    /**
    * Here you can find all documents created for the piece's QRcode
    */
    'documents'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInnerDocumentsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "referenceNumber",
            "baseName": "referenceNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "trackingNumber",
            "baseName": "trackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "trackingUrl",
            "baseName": "trackingUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "volumetricWeight",
            "baseName": "volumetricWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInnerDocumentsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentResponsePackagesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

