/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MonetaryAmountInner } from './MonetaryAmountInner';
import { SupermodelIoLogisticsExpressAccount } from './SupermodelIoLogisticsExpressAccount';
import { SupermodelIoLogisticsExpressPackageRR } from './SupermodelIoLogisticsExpressPackageRR';
import { SupermodelIoLogisticsExpressRateRequestCustomerDetails } from './SupermodelIoLogisticsExpressRateRequestCustomerDetails';
import { SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner } from './SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner';
import { SupermodelIoLogisticsExpressValueAddedServicesRates } from './SupermodelIoLogisticsExpressValueAddedServicesRates';
import { HttpFile } from '../http/http';

/**
* Definition of /rates request message
*/
export class SupermodelIoLogisticsExpressRateRequest {
    'customerDetails': SupermodelIoLogisticsExpressRateRequestCustomerDetails;
    /**
    * Please enter all the DHL Express accounts and types to be used for this shipment
    */
    'accounts'?: Array<SupermodelIoLogisticsExpressAccount>;
    /**
    * Please enter DHL Express Global Product code
    */
    'productCode'?: string;
    /**
    * Please enter DHL Express Local Product code
    */
    'localProductCode'?: string;
    /**
    * Please use if you wish to filter the response by value added services
    */
    'valueAddedServices'?: Array<SupermodelIoLogisticsExpressValueAddedServicesRates>;
    /**
    * Please use if you wish to filter the response by product(s) and/or value added services
    */
    'productsAndServices'?: Array<SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner>;
    /**
    * payerCountryCode is to be provided if your profile has been enabled to view rates without an account number (this will provide DHL Express published rates for the payer country)
    */
    'payerCountryCode'?: string;
    /**
    * Identifies the date and time the package is tendered. Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).
    */
    'plannedShippingDateAndTime': string;
    /**
    * Please enter Unit of measurement - metric,imperial
    */
    'unitOfMeasurement': SupermodelIoLogisticsExpressRateRequestUnitOfMeasurementEnum;
    /**
    * For customs purposes please advise if your shipment is dutiable (true) or non dutiable (false)
    */
    'isCustomsDeclarable': boolean;
    /**
    * Please provide monetary amount related to your shipment, for example shipment declared value
    */
    'monetaryAmount'?: Array<MonetaryAmountInner>;
    /**
    * Please set this to ture to receive all valuda added services for each product availabe
    */
    'requestAllValueAddedServices'?: boolean;
    /**
    * Please set this to true to filter out all products which needs DHL Express special customer agreement
    */
    'returnStandardProductsOnly'?: boolean;
    /**
    * Please set this to true in case you want to receive products which are not available on planned shipping date but next available day
    */
    'nextBusinessDay'?: boolean;
    /**
    * Please select which type of priducts you are interested in
    */
    'productTypeCode'?: SupermodelIoLogisticsExpressRateRequestProductTypeCodeEnum;
    /**
    * Here you can define properties per package
    */
    'packages': Array<SupermodelIoLogisticsExpressPackageRR>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerDetails",
            "baseName": "customerDetails",
            "type": "SupermodelIoLogisticsExpressRateRequestCustomerDetails",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<SupermodelIoLogisticsExpressAccount>",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCode",
            "baseName": "localProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "valueAddedServices",
            "baseName": "valueAddedServices",
            "type": "Array<SupermodelIoLogisticsExpressValueAddedServicesRates>",
            "format": ""
        },
        {
            "name": "productsAndServices",
            "baseName": "productsAndServices",
            "type": "Array<SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner>",
            "format": ""
        },
        {
            "name": "payerCountryCode",
            "baseName": "payerCountryCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedShippingDateAndTime",
            "baseName": "plannedShippingDateAndTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitOfMeasurement",
            "baseName": "unitOfMeasurement",
            "type": "SupermodelIoLogisticsExpressRateRequestUnitOfMeasurementEnum",
            "format": ""
        },
        {
            "name": "isCustomsDeclarable",
            "baseName": "isCustomsDeclarable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "monetaryAmount",
            "baseName": "monetaryAmount",
            "type": "Array<MonetaryAmountInner>",
            "format": ""
        },
        {
            "name": "requestAllValueAddedServices",
            "baseName": "requestAllValueAddedServices",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "returnStandardProductsOnly",
            "baseName": "returnStandardProductsOnly",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "nextBusinessDay",
            "baseName": "nextBusinessDay",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "productTypeCode",
            "baseName": "productTypeCode",
            "type": "SupermodelIoLogisticsExpressRateRequestProductTypeCodeEnum",
            "format": ""
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<SupermodelIoLogisticsExpressPackageRR>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressRateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressRateRequestUnitOfMeasurementEnum = "metric" | "imperial" ;
export type SupermodelIoLogisticsExpressRateRequestProductTypeCodeEnum = "all" | "dayDefinite" | "timeDefinite" ;

