/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressAccount } from './SupermodelIoLogisticsExpressAccount';
import { SupermodelIoLogisticsExpressPickupRequestCustomerDetails } from './SupermodelIoLogisticsExpressPickupRequestCustomerDetails';
import { SupermodelIoLogisticsExpressPickupRequestSpecialInstructionsInner } from './SupermodelIoLogisticsExpressPickupRequestSpecialInstructionsInner';
import { SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetailsInner } from './SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetailsInner';
import { HttpFile } from '../http/http';

/**
* UpdatePickup schema definition
*/
export class SupermodelIoLogisticsExpressUpdatePickupRequest {
    /**
    * Please enter Dispatch confirmation number which identifies the already scheduled pickup
    */
    'dispatchConfirmationNumber': string;
    /**
    * Please enter the shipper account number which was used during the scheduled pickup creation
    */
    'originalShipperAccountNumber': string;
    /**
    * Identifies the date and time the package is ready for pickup Both the date and time portions of the string are expected to be used. The date should not be a past date or a date more than 10 days in the future. The time is the local time of the shipment based on the shipper's time zone. The date component must be in the format: YYYY-MM-DD; the time component must be in the format: HH:MM:SS using a 24 hour clock. The date and time parts are separated by the letter T (e.g. 2006-06-26T17:00:00 GMT+01:00).<BR>                           
    */
    'plannedPickupDateAndTime': string;
    /**
    * The latest time the location premises is available to dispatch the DHL Express shipment. (HH:MM) 
    */
    'closeTime'?: string;
    /**
    * Provides information on where the package should be picked up by DHL courier. <BR>                           
    */
    'location'?: string;
    /**
    * Provides information on where the package should be picked up by DHL courier. <BR>                           
    */
    'locationType'?: SupermodelIoLogisticsExpressUpdatePickupRequestLocationTypeEnum;
    'accounts': Array<SupermodelIoLogisticsExpressAccount>;
    /**
    * Details special pickup instructions you may wish to send to the DHL Courier.
    */
    'specialInstructions'?: Array<SupermodelIoLogisticsExpressPickupRequestSpecialInstructionsInner>;
    /**
    * Please provide additional pickup remark
    */
    'remark'?: string;
    'customerDetails': SupermodelIoLogisticsExpressPickupRequestCustomerDetails;
    /**
    * Please provide updated details related to shipment you want update the pickup for
    */
    'shipmentDetails'?: Array<SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetailsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "dispatchConfirmationNumber",
            "baseName": "dispatchConfirmationNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "originalShipperAccountNumber",
            "baseName": "originalShipperAccountNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "plannedPickupDateAndTime",
            "baseName": "plannedPickupDateAndTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "closeTime",
            "baseName": "closeTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "locationType",
            "baseName": "locationType",
            "type": "SupermodelIoLogisticsExpressUpdatePickupRequestLocationTypeEnum",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<SupermodelIoLogisticsExpressAccount>",
            "format": ""
        },
        {
            "name": "specialInstructions",
            "baseName": "specialInstructions",
            "type": "Array<SupermodelIoLogisticsExpressPickupRequestSpecialInstructionsInner>",
            "format": ""
        },
        {
            "name": "remark",
            "baseName": "remark",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerDetails",
            "baseName": "customerDetails",
            "type": "SupermodelIoLogisticsExpressPickupRequestCustomerDetails",
            "format": ""
        },
        {
            "name": "shipmentDetails",
            "baseName": "shipmentDetails",
            "type": "Array<SupermodelIoLogisticsExpressUpdatePickupRequestShipmentDetailsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressUpdatePickupRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressUpdatePickupRequestLocationTypeEnum = "business" | "residence" ;

