/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressValueAddedServicesRates {
    /**
    * Please enter DHL Express value added global service code. For detailed list of all available service codes for your prospect shipment please invoke /products or /rates
    */
    'serviceCode': string;
    /**
    * Please enter DHL Express value added local service code. For detailed list of all available service codes for your prospect shipment please invoke /products or /rates
    */
    'localServiceCode'?: string;
    /**
    * Please enter monetary value of service (e.g. Insured Value)
    */
    'value'?: number;
    /**
    * Please enter currency code (e.g. Insured Value currency code)
    */
    'currency'?: string;
    /**
    * For future use
    */
    'method'?: SupermodelIoLogisticsExpressValueAddedServicesRatesMethodEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "serviceCode",
            "baseName": "serviceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localServiceCode",
            "baseName": "localServiceCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "string",
            "format": ""
        },
        {
            "name": "method",
            "baseName": "method",
            "type": "SupermodelIoLogisticsExpressValueAddedServicesRatesMethodEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressValueAddedServicesRates.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressValueAddedServicesRatesMethodEnum = "cash" ;

