/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerCustomerDetails } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerCustomerDetails';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerDestinationServiceArea } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerDestinationServiceArea';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerOriginServiceArea } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerOriginServiceArea';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerPickupDetails } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerPickupDetails';
import { SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerValueAddedServicesInner } from './SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerValueAddedServicesInner';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner {
    /**
    * This array contains all the DHL Express special handling feature codes
    */
    'serviceHandlingFeatureCodes'?: Array<string>;
    /**
    * Here you can find calculated volumetric weight based on dimensions provided in the request
    */
    'volumetricWeight'?: number;
    /**
    * Here you can find billing code which was applied on your shipment
    */
    'billingCode'?: string;
    /**
    * Here you can find the DHL Express shipment content code of your shipment
    */
    'serviceContentCode'?: string;
    'customerDetails'?: SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerCustomerDetails;
    'originServiceArea'?: SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerOriginServiceArea;
    'destinationServiceArea'?: SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerDestinationServiceArea;
    /**
    * Here you can find DHL Routing Code which was applied on your shipment
    */
    'dhlRoutingCode'?: string;
    /**
    * Here you can find DHL Routing Data ID which was applied on your shipment
    */
    'dhlRoutingDataId'?: string;
    /**
    * Here you can find Delivery Date Code which was applied on your shipment
    */
    'deliveryDateCode'?: string;
    /**
    * Here you can find Delivery Time Code which was applied on your shipment
    */
    'deliveryTimeCode'?: string;
    /**
    * Here you can find the product short name of your shipment
    */
    'productShortName'?: string;
    'valueAddedServices'?: Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerValueAddedServicesInner>;
    'pickupDetails'?: SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerPickupDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "serviceHandlingFeatureCodes",
            "baseName": "serviceHandlingFeatureCodes",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "volumetricWeight",
            "baseName": "volumetricWeight",
            "type": "number",
            "format": ""
        },
        {
            "name": "billingCode",
            "baseName": "billingCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceContentCode",
            "baseName": "serviceContentCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "customerDetails",
            "baseName": "customerDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerCustomerDetails",
            "format": ""
        },
        {
            "name": "originServiceArea",
            "baseName": "originServiceArea",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerOriginServiceArea",
            "format": ""
        },
        {
            "name": "destinationServiceArea",
            "baseName": "destinationServiceArea",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerDestinationServiceArea",
            "format": ""
        },
        {
            "name": "dhlRoutingCode",
            "baseName": "dhlRoutingCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "dhlRoutingDataId",
            "baseName": "dhlRoutingDataId",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryDateCode",
            "baseName": "deliveryDateCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "deliveryTimeCode",
            "baseName": "deliveryTimeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "productShortName",
            "baseName": "productShortName",
            "type": "string",
            "format": ""
        },
        {
            "name": "valueAddedServices",
            "baseName": "valueAddedServices",
            "type": "Array<SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerValueAddedServicesInner>",
            "format": ""
        },
        {
            "name": "pickupDetails",
            "baseName": "pickupDetails",
            "type": "SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInnerPickupDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressCreateShipmentResponseShipmentDetailsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

