/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressValueAddedServicesRates } from './SupermodelIoLogisticsExpressValueAddedServicesRates';
import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner {
    /**
    * Please enter DHL Express Global Product code
    */
    'productCode': string;
    /**
    * Please enter DHL Express Local Product code
    */
    'localProductCode'?: string;
    /**
    * Please use if you wish to filter the response by value added services
    */
    'valueAddedServices'?: Array<SupermodelIoLogisticsExpressValueAddedServicesRates>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCode",
            "baseName": "localProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "valueAddedServices",
            "baseName": "valueAddedServices",
            "type": "Array<SupermodelIoLogisticsExpressValueAddedServicesRates>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressRateRequestProductsAndServicesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

