/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SupermodelIoLogisticsExpressDocumentImageResponseDocumentsInner {
    /**
    * Shipment Tracking Number
    */
    'shipmentTrackingNumber': string;
    /**
    * Identifies type of the document like commercial invoice or waybill, or archived zip documents
    */
    'typeCode': string;
    /**
    * Clearance code or document function whether for import, export or both.  Returned only for customs-entry
    */
    '_function'?: SupermodelIoLogisticsExpressDocumentImageResponseDocumentsInnerFunctionEnum;
    /**
    * Identifies image format the document is created in, like PDF, TIFF, or ZIP
    */
    'encodingFormat': string;
    /**
    * Contains base64 encoded document image or archived zip
    */
    'content': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "shipmentTrackingNumber",
            "baseName": "shipmentTrackingNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "typeCode",
            "baseName": "typeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "_function",
            "baseName": "function",
            "type": "SupermodelIoLogisticsExpressDocumentImageResponseDocumentsInnerFunctionEnum",
            "format": ""
        },
        {
            "name": "encodingFormat",
            "baseName": "encodingFormat",
            "type": "string",
            "format": ""
        },
        {
            "name": "content",
            "baseName": "content",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressDocumentImageResponseDocumentsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressDocumentImageResponseDocumentsInnerFunctionEnum = "import" | "export" | "both" ;

