/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressAccount } from './SupermodelIoLogisticsExpressAccount';
import { SupermodelIoLogisticsExpressLandedCostRequestChargesInner } from './SupermodelIoLogisticsExpressLandedCostRequestChargesInner';
import { SupermodelIoLogisticsExpressLandedCostRequestCustomerDetails } from './SupermodelIoLogisticsExpressLandedCostRequestCustomerDetails';
import { SupermodelIoLogisticsExpressLandedCostRequestItemsInner } from './SupermodelIoLogisticsExpressLandedCostRequestItemsInner';
import { SupermodelIoLogisticsExpressPackageRR } from './SupermodelIoLogisticsExpressPackageRR';
import { HttpFile } from '../http/http';

/**
* Landed cost request model description
*/
export class SupermodelIoLogisticsExpressLandedCostRequest {
    'customerDetails': SupermodelIoLogisticsExpressLandedCostRequestCustomerDetails;
    /**
    * Please enter all the DHL Express accounts and types to be used for this shipment
    */
    'accounts': Array<SupermodelIoLogisticsExpressAccount>;
    /**
    * Please enter DHL Express Global Product code
    */
    'productCode'?: string;
    /**
    * Please enter DHL Express Local Product code
    */
    'localProductCode'?: string;
    /**
    * Please enter Unit of measurement - metric,imperial
    */
    'unitOfMeasurement': SupermodelIoLogisticsExpressLandedCostRequestUnitOfMeasurementEnum;
    /**
    * Currency code for the item price (the product being sold) and freight charge. The Landed Cost calculation result will be returned in this defined currency
    */
    'currencyCode': string;
    /**
    * Set this to true is shipment contains declarable content
    */
    'isCustomsDeclarable': boolean;
    /**
    * Set this to true if you want DHL EXpress product Duties and Taxes Paid outside shipment destination
    */
    'isDTPRequested'?: boolean;
    /**
    * Set this true if you ask for DHL Express insurance service
    */
    'isInsuranceRequested'?: boolean;
    /**
    * Allowed values 'true' - item cost breakdown will be returned, 'false' - item cost breakdown will not be returned
    */
    'getCostBreakdown': boolean;
    /**
    * Please provide any additional charges you would like to include in total cost calculation
    */
    'charges'?: Array<SupermodelIoLogisticsExpressLandedCostRequestChargesInner>;
    /**
    * Possible values:<BR>      commercial: B2B<BR>      personal: B2C<BR>      commercia': B2B<BR>      personal: B2C
    */
    'shipmentPurpose'?: SupermodelIoLogisticsExpressLandedCostRequestShipmentPurposeEnum;
    'transportationMode'?: SupermodelIoLogisticsExpressLandedCostRequestTransportationModeEnum;
    /**
    * Carrier being used to ship with. Allowed values are:<BR>      'DHL','UPS','FEDEX','TNT','POST',<BR>      'OTHERS'
    */
    'merchantSelectedCarrierName'?: SupermodelIoLogisticsExpressLandedCostRequestMerchantSelectedCarrierNameEnum;
    /**
    * Here you can define properties per package
    */
    'packages': Array<SupermodelIoLogisticsExpressPackageRR>;
    'items': Array<SupermodelIoLogisticsExpressLandedCostRequestItemsInner>;
    /**
    * Allowed values 'true' - tariff formula on item and shipment level will be returned, 'false' - tariff formula on item and shipment level will not be returned
    */
    'getTariffFormula'?: boolean;
    /**
    * Allowed values 'true' - quotation ID on shipment level will be returned, 'false' - quotation ID on shipment level will not be returned
    */
    'getQuotationID'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerDetails",
            "baseName": "customerDetails",
            "type": "SupermodelIoLogisticsExpressLandedCostRequestCustomerDetails",
            "format": ""
        },
        {
            "name": "accounts",
            "baseName": "accounts",
            "type": "Array<SupermodelIoLogisticsExpressAccount>",
            "format": ""
        },
        {
            "name": "productCode",
            "baseName": "productCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "localProductCode",
            "baseName": "localProductCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "unitOfMeasurement",
            "baseName": "unitOfMeasurement",
            "type": "SupermodelIoLogisticsExpressLandedCostRequestUnitOfMeasurementEnum",
            "format": ""
        },
        {
            "name": "currencyCode",
            "baseName": "currencyCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "isCustomsDeclarable",
            "baseName": "isCustomsDeclarable",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isDTPRequested",
            "baseName": "isDTPRequested",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "isInsuranceRequested",
            "baseName": "isInsuranceRequested",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "getCostBreakdown",
            "baseName": "getCostBreakdown",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "charges",
            "baseName": "charges",
            "type": "Array<SupermodelIoLogisticsExpressLandedCostRequestChargesInner>",
            "format": ""
        },
        {
            "name": "shipmentPurpose",
            "baseName": "shipmentPurpose",
            "type": "SupermodelIoLogisticsExpressLandedCostRequestShipmentPurposeEnum",
            "format": ""
        },
        {
            "name": "transportationMode",
            "baseName": "transportationMode",
            "type": "SupermodelIoLogisticsExpressLandedCostRequestTransportationModeEnum",
            "format": ""
        },
        {
            "name": "merchantSelectedCarrierName",
            "baseName": "merchantSelectedCarrierName",
            "type": "SupermodelIoLogisticsExpressLandedCostRequestMerchantSelectedCarrierNameEnum",
            "format": ""
        },
        {
            "name": "packages",
            "baseName": "packages",
            "type": "Array<SupermodelIoLogisticsExpressPackageRR>",
            "format": ""
        },
        {
            "name": "items",
            "baseName": "items",
            "type": "Array<SupermodelIoLogisticsExpressLandedCostRequestItemsInner>",
            "format": ""
        },
        {
            "name": "getTariffFormula",
            "baseName": "getTariffFormula",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "getQuotationID",
            "baseName": "getQuotationID",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressLandedCostRequest.attributeTypeMap;
    }

    public constructor() {
    }
}


export type SupermodelIoLogisticsExpressLandedCostRequestUnitOfMeasurementEnum = "metric" | "imperial" ;
export type SupermodelIoLogisticsExpressLandedCostRequestShipmentPurposeEnum = "commercial" | "personal" ;
export type SupermodelIoLogisticsExpressLandedCostRequestTransportationModeEnum = "air" | "ocean" | "ground" ;
export type SupermodelIoLogisticsExpressLandedCostRequestMerchantSelectedCarrierNameEnum = "DHL" | "UPS" | "FEDEX" | "TNT" | "POST" | "OTHERS" ;

