/**
 * DHL Express APIs (MyDHL API)
 * Welcome to the official DHL Express APIs (MyDHL API) below are the published API Documentation to fulfill your shipping needs with DHL Express.       Please follow the process described [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--get-access) to request access to the DHL Express - MyDHL API services    In case you already have DHL Express - MyDHL API Service credentials please ensure to use the endpoints/environments listed  [here](https://developer.dhl.com/api-reference/dhl-express-mydhl-api#get-started-section/user-guide--environments) 
 *
 * OpenAPI spec version: 2.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsBuyerDetails } from './SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsBuyerDetails';
import { SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsExporterDetails } from './SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsExporterDetails';
import { SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsImporterDetails } from './SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsImporterDetails';
import { SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsSellerDetails } from './SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsSellerDetails';
import { HttpFile } from '../http/http';

/**
* Here you need to define all the parties needed to ship the package
*/
export class SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetails {
    'sellerDetails'?: SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsSellerDetails;
    'buyerDetails'?: SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsBuyerDetails;
    'importerDetails'?: SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsImporterDetails;
    'exporterDetails'?: SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsExporterDetails;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "sellerDetails",
            "baseName": "sellerDetails",
            "type": "SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsSellerDetails",
            "format": ""
        },
        {
            "name": "buyerDetails",
            "baseName": "buyerDetails",
            "type": "SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsBuyerDetails",
            "format": ""
        },
        {
            "name": "importerDetails",
            "baseName": "importerDetails",
            "type": "SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsImporterDetails",
            "format": ""
        },
        {
            "name": "exporterDetails",
            "baseName": "exporterDetails",
            "type": "SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetailsExporterDetails",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SupermodelIoLogisticsExpressUploadInvoiceDataRequestCustomerDetails.attributeTypeMap;
    }

    public constructor() {
    }
}

